name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - staging

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
