name: Push 2 branchs

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: push changes to remote
      run: |

        git checkout staging
        git reset --hard origin/master
        git push -f origin staging

          
