name: Push 2 branchs

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: push changes to remote
      run: |

        git checkout staging
        git reset --hard origin/master
        git push -f origin staging

          
