name: Push 2 branchs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: push changes to remote
        run: |
          git config --global user.name "Camille Coutens"
          git config --global user.email "camille@japhy.fr"

          git checkout staging
          git reset --hard origin/master
          git push -f origin staging
          
